name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
        uses: actions/checkout@master
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.mt-develop.com
          username: u744866482
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./